/*
 * Copyright (c) 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.faendir.zachtronics.bot.om.model

import com.faendir.zachtronics.bot.model.Category
import com.faendir.zachtronics.bot.om.model.OmMetric.*
import com.faendir.zachtronics.bot.om.model.OmScoreManifold.*


enum class OmCategory(
    val manifold: OmScoreManifold,
    private val admission: OmMetric<Boolean>,
    vararg metricsVararg: OmMetric<*>,
    override val displayName: String = admission.displayName + metricsVararg.take(2).joinToString("") { it.displayName },
) : Category {
    GC(VICTORY_AREA, NOVERLAP, COST, CYCLES, AREA),
    GC_P(VICTORY_PROD, NOVERLAP, COST, CYCLES, INSTRUCTIONS),
    GA(VICTORY_AREA, NOVERLAP, COST, AREA, CYCLES),
    GI(VICTORY_AREA, NOVERLAP, COST, INSTRUCTIONS, CYCLES, AREA),
    GI_P(VICTORY_PROD, NOVERLAP, COST, INSTRUCTIONS, CYCLES),
    GX(VICTORY_AREA, NOVERLAP, COST, PRODUCT_CA),
    GX_P(VICTORY_PROD, NOVERLAP, COST, PRODUCT_CI),

    CG(VICTORY_AREA, NOVERLAP, CYCLES, COST, AREA),
    CG_P(VICTORY_PROD, NOVERLAP, CYCLES, COST, INSTRUCTIONS),
    CA(VICTORY_AREA, NOVERLAP, CYCLES, AREA, COST),
    CI(VICTORY_AREA, NOVERLAP, CYCLES, INSTRUCTIONS, COST, AREA),
    CI_P(VICTORY_PROD, NOVERLAP, CYCLES, INSTRUCTIONS, COST),
    CX(VICTORY_AREA, NOVERLAP, CYCLES, PRODUCT_GA),
    CX_P(VICTORY_PROD, NOVERLAP, CYCLES, PRODUCT_GI),

    AG(VICTORY_AREA, NOVERLAP, AREA, COST, CYCLES),
    AC(VICTORY_AREA, NOVERLAP, AREA, CYCLES, COST),
    AX(VICTORY_AREA, NOVERLAP, AREA, PRODUCT_GC),
    AI(VICTORY_AREA, NOVERLAP, AREA, INSTRUCTIONS, COST, CYCLES),

    IG(VICTORY_AREA, NOVERLAP, INSTRUCTIONS, COST, CYCLES, AREA),
    IG_P(VICTORY_PROD, NOVERLAP, INSTRUCTIONS, COST, CYCLES),
    IC(VICTORY_AREA, NOVERLAP, INSTRUCTIONS, CYCLES, COST, AREA),
    IC_P(VICTORY_PROD, NOVERLAP, INSTRUCTIONS, CYCLES, COST),
    IA(VICTORY_AREA, NOVERLAP, INSTRUCTIONS, AREA, COST, CYCLES),
    IX_P(VICTORY_PROD, NOVERLAP, INSTRUCTIONS, PRODUCT_GC),

    SUM(VICTORY_AREA, NOVERLAP, SUM3A, displayName = "Sum"),
    SUM_P(VICTORY_PROD, NOVERLAP, SUM3I, displayName = "Sum"),

    SUM4(VICTORY_AREA, NOVERLAP, OmMetric.SUM4, displayName = "Sum4"),

    HG(VICTORY_HEIGHT, NOVERLAP, HEIGHT, COST, CYCLES),
    HC(VICTORY_HEIGHT, NOVERLAP, HEIGHT, CYCLES, COST),
    WG(VICTORY_WIDTH, NOVERLAP, WIDTH, COST, CYCLES),
    WC(VICTORY_WIDTH, NOVERLAP, WIDTH, CYCLES, COST),
    BG(VICTORY_BHEX, NOVERLAP, BOUNDING_HEX, COST, CYCLES),
    BC(VICTORY_BHEX, NOVERLAP, BOUNDING_HEX, CYCLES, COST),

    OGC(VICTORY_AREA, ANYTHING_GOES, COST, CYCLES, AREA, NOVERLAP),
    OCX(VICTORY_AREA, ANYTHING_GOES, CYCLES, PRODUCT_GA, NOVERLAP),
    OAC(VICTORY_AREA, ANYTHING_GOES, AREA, CYCLES, COST, NOVERLAP),
    OIC(VICTORY_AREA, ANYTHING_GOES, INSTRUCTIONS, CYCLES, COST, AREA, NOVERLAP),

    OGC_P(VICTORY_PROD, ANYTHING_GOES, COST, CYCLES, INSTRUCTIONS, NOVERLAP),
    OCX_P(VICTORY_PROD, ANYTHING_GOES, CYCLES, PRODUCT_GI, NOVERLAP),
    OIC_P(VICTORY_PROD, ANYTHING_GOES, INSTRUCTIONS, CYCLES, COST, NOVERLAP),

    OSUM(VICTORY_AREA, ANYTHING_GOES, SUM3A, NOVERLAP, displayName = "OSum"),
    OSUM_P(VICTORY_PROD, ANYTHING_GOES, SUM3I, NOVERLAP, displayName = "OSum"),

    OSUM4(VICTORY_AREA, ANYTHING_GOES, OmMetric.SUM4, NOVERLAP, displayName = "OSum4"),

    TIG(VICTORY_AREA, NOVERLAP_TRACKLESS, INSTRUCTIONS, COST, CYCLES, AREA),
    TIC(VICTORY_AREA, NOVERLAP_TRACKLESS, INSTRUCTIONS, CYCLES, COST, AREA),
    TIA(INFINITY_AREA, NOVERLAP_TRACKLESS, INSTRUCTIONS, AREA_INF, COST, RATE),

    TIG_P(VICTORY_PROD, NOVERLAP_TRACKLESS, INSTRUCTIONS, COST, CYCLES),
    TIC_P(VICTORY_PROD, NOVERLAP_TRACKLESS, INSTRUCTIONS, CYCLES, COST),

    TG(VICTORY_AREA, NOVERLAP_TRACKLESS, COST, CYCLES, AREA, displayName = "TG"),
    TC(VICTORY_AREA, NOVERLAP_TRACKLESS, CYCLES, COST, AREA, displayName = "TC"),

    TG_P(VICTORY_PROD, NOVERLAP_TRACKLESS, COST, CYCLES, INSTRUCTIONS, displayName = "TG"),
    TC_P(VICTORY_PROD, NOVERLAP_TRACKLESS, CYCLES, COST, INSTRUCTIONS, displayName = "TC"),

    RG(INFINITY_AREA, NOVERLAP, RATE, COST, AREA_INF),
    RG_P(INFINITY_PROD, NOVERLAP, RATE, COST, INSTRUCTIONS),
    RA(INFINITY_AREA, NOVERLAP, RATE, AREA_INF, COST),
    RI(INFINITY_AREA, NOVERLAP, RATE, INSTRUCTIONS, COST, AREA_INF),
    RI_P(INFINITY_PROD, NOVERLAP, RATE, INSTRUCTIONS, COST),

    HR(INFINITY_HEIGHT, NOVERLAP, HEIGHT_INF, RATE, COST),
    WR(INFINITY_WIDTH, NOVERLAP, WIDTH_INF, RATE, COST),
    BR(INFINITY_BHEX, NOVERLAP, BOUNDING_HEX_INF, RATE, COST),

    ORG(INFINITY_AREA, ANYTHING_GOES, RATE, COST, AREA_INF, NOVERLAP),
    ORX(INFINITY_AREA, ANYTHING_GOES, RATE, PRODUCT_GI, AREA_INF, NOVERLAP),

    ORG_P(INFINITY_PROD, ANYTHING_GOES, RATE, COST, INSTRUCTIONS, NOVERLAP),
    ORX_P(INFINITY_PROD, ANYTHING_GOES, RATE, PRODUCT_GI, NOVERLAP),

    // ADDED
    GH(VICTORY_HEIGHT, NOVERLAP, COST, HEIGHT, CYCLES),
    GW(VICTORY_WIDTH, NOVERLAP, COST, WIDTH, CYCLES),
    GB(VICTORY_BHEX, NOVERLAP, COST, BOUNDING_HEX, CYCLES),

    CH(VICTORY_HEIGHT, NOVERLAP, CYCLES, HEIGHT, COST),
    CW(VICTORY_WIDTH, NOVERLAP, CYCLES, WIDTH, COST),
    CB(VICTORY_BHEX, NOVERLAP, CYCLES, BOUNDING_HEX, COST),

    IH(VICTORY_HEIGHT, NOVERLAP, INSTRUCTIONS, HEIGHT, COST, CYCLES),
    IW(VICTORY_WIDTH, NOVERLAP, INSTRUCTIONS, WIDTH, COST, CYCLES),
    IB(VICTORY_BHEX, NOVERLAP, INSTRUCTIONS, BOUNDING_HEX, COST, CYCLES),

    HI(VICTORY_HEIGHT, NOVERLAP, HEIGHT, INSTRUCTIONS, COST, CYCLES),
    WI(VICTORY_WIDTH, NOVERLAP, WIDTH, INSTRUCTIONS, COST, CYCLES),
    BI(VICTORY_BHEX, NOVERLAP, BOUNDING_HEX, INSTRUCTIONS, COST, CYCLES),

    HX(VICTORY_HEIGHT, NOVERLAP, HEIGHT, PRODUCT_GC),
    WX(VICTORY_WIDTH, NOVERLAP, WIDTH, PRODUCT_GC),
    BX(VICTORY_BHEX, NOVERLAP, BOUNDING_HEX, PRODUCT_GC),

    GR(INFINITY_AREA, NOVERLAP, COST, RATE, AREA_INF),
    GR_P(INFINITY_PROD, NOVERLAP, COST, RATE, INSTRUCTIONS), 
    AR(INFINITY_AREA, NOVERLAP, AREA_INF, RATE, COST),
    IR(INFINITY_AREA, NOVERLAP, INSTRUCTIONS, RATE, COST, AREA_INF),
    IR_P(INFINITY_PROD, NOVERLAP, INSTRUCTIONS, RATE, COST),

    RH(INFINITY_HEIGHT, NOVERLAP, RATE, HEIGHT_INF, COST),
    RW(INFINITY_WIDTH, NOVERLAP, RATE, WIDTH_INF, COST),
    RB(INFINITY_BHEX, NOVERLAP, RATE, BOUNDING_HEX_INF, COST),

    // CXH(VICTORY_HEIGHT, NOVERLAP, CYCLES, PRODUCT_GH, displayName = "CXH"),
    // CXW(VICTORY_WIDTH, NOVERLAP, CYCLES, PRODUCT_GW, displayName = "CXW"),
    // CXB(VICTORY_BHEX, NOVERLAP, CYCLES, PRODUCT_GB, displayName = "CXB"),

    // OCXH(VICTORY_HEIGHT, ANYTHING_GOES, CYCLES, PRODUCT_GH, NOVERLAP, displayName = "OCXH"),
    // OCXW(VICTORY_WIDTH, ANYTHING_GOES, CYCLES, PRODUCT_GW, NOVERLAP, displayName = "OCXW"),
    // OCXB(VICTORY_BHEX, ANYTHING_GOES, CYCLES, PRODUCT_GB, NOVERLAP, displayName = "OCXB"),

    // GXH(VICTORY_HEIGHT, NOVERLAP, COST, PRODUCT_CH, displayName = "GXH"),
    // GXW(VICTORY_WIDTH, NOVERLAP, COST, PRODUCT_CW, displayName = "GXW"),
    // GXB(VICTORY_BHEX, NOVERLAP, COST, PRODUCT_CB, displayName = "GXB"),

    // SUMH(VICTORY_HEIGHT, NOVERLAP, SUM3H, displayName = "SumH"),
    // SUMW(VICTORY_WIDTH, NOVERLAP, SUM3W, displayName = "SumW"),
    // SUMB(VICTORY_BHEX, NOVERLAP, SUM3B, displayName = "SumB"),

    // SUM4H(VICTORY_HEIGHT, NOVERLAP, OmMetric.SUM4H, displayName = "Sum4H"),
    // SUM4W(VICTORY_WIDTH, NOVERLAP, OmMetric.SUM4W, displayName = "Sum4W"),
    // SUM4B(VICTORY_BHEX, NOVERLAP, OmMetric.SUM4B, displayName = "Sum4B"),

    // OSUMH(VICTORY_HEIGHT, ANYTHING_GOES, SUM3H, NOVERLAP, displayName = "OSumH"),
    // OSUMW(VICTORY_WIDTH, ANYTHING_GOES, SUM3W, NOVERLAP, displayName = "OSumW"),
    // OSUMB(VICTORY_BHEX, ANYTHING_GOES, SUM3B, NOVERLAP, displayName = "OSumB"),

    // OSUM4H(VICTORY_HEIGHT, ANYTHING_GOES, OmMetric.SUM4H, NOVERLAP, displayName = "OSum4H"),
    // OSUM4W(VICTORY_WIDTH, ANYTHING_GOES, OmMetric.SUM4W, NOVERLAP, displayName = "OSum4W"),
    // OSUM4B(VICTORY_BHEX, ANYTHING_GOES, OmMetric.SUM4B, NOVERLAP, displayName = "OSum4B"),

    PRODUCT(VICTORY_AREA, NOVERLAP, PRODUCT_GCA, displayName = "Product"),
    PRODUCT_P(VICTORY_PROD, NOVERLAP, PRODUCT_GCI, displayName = "Product"),

    PRODUCT4(VICTORY_AREA, NOVERLAP, PRODUCT_GCAI, displayName = "Product4"),

    OPRODUCT(VICTORY_AREA, ANYTHING_GOES, PRODUCT_GCA, NOVERLAP, displayName = "OProduct"),
    OPRODUCT_P(VICTORY_PROD, ANYTHING_GOES, PRODUCT_GCI, NOVERLAP, displayName = "OProduct"),

    OPRODUCT4(VICTORY_AREA, ANYTHING_GOES, PRODUCT_GCAI, NOVERLAP, displayName = "OProduct4"),

    // PRODUCTH(VICTORY_HEIGHT, NOVERLAP, PRODUCT_GCH, displayName = "ProductH"),
    // PRODUCTW(VICTORY_WIDTH, NOVERLAP, PRODUCT_GCW, displayName = "ProductW"),
    // PRODUCTB(VICTORY_BHEX, NOVERLAP, PRODUCT_GCB, displayName = "ProductB"),

    // PRODUCT4H(VICTORY_HEIGHT, NOVERLAP, PRODUCT_GCHI, displayName = "Product4H"),
    // PRODUCT4W(VICTORY_WIDTH, NOVERLAP, PRODUCT_GCWI, displayName = "Product4W"),
    // PRODUCT4B(VICTORY_BHEX, NOVERLAP, PRODUCT_GCBI, displayName = "Product4B"),

    // OPRODUCTH(VICTORY_HEIGHT, ANYTHING_GOES, PRODUCT_GCH, NOVERLAP, displayName = "OProductH"),
    // OPRODUCTW(VICTORY_WIDTH, ANYTHING_GOES, PRODUCT_GCW, NOVERLAP, displayName = "OProductW"),
    // OPRODUCTB(VICTORY_BHEX, ANYTHING_GOES, PRODUCT_GCB, NOVERLAP, displayName = "OProductB"),

    // OPRODUCT4H(VICTORY_HEIGHT, ANYTHING_GOES, PRODUCT_GCHI, NOVERLAP, displayName = "OProduct4H"),
    // OPRODUCT4W(VICTORY_WIDTH, ANYTHING_GOES, PRODUCT_GCWI, NOVERLAP, displayName = "OProduct4W"),
    // OPRODUCT4B(VICTORY_BHEX, ANYTHING_GOES, PRODUCT_GCBI, NOVERLAP, displayName = "OProduct4B"),
    ;

    override val supportedTypes: Set<OmType> by manifold::supportedTypes
    override val metrics: List<OmMetric<*>> = listOf(admission) + metricsVararg
    val requiredParts: Set<ScorePart<*>> = metrics.flatMapTo(HashSet()) { it.scoreParts }
    val scoreComparator: Comparator<OmScore> =
        (metrics + (manifold.scoreParts - metrics)).reduce(Comparator<OmScore>::then)

    fun supportsPuzzle(puzzle: OmPuzzle) = supportedTypes.contains(puzzle.type)

    fun supportsScore(score: OmScore) = manifold.supportsScore(score) && admission.getValueFrom(score)
}
